amp_backend: native
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
check_val_every_n_epoch: 1
data_annot_bndry_dir: /mnt/isilon/skali/CC3D_filter/cc3d_v1.0_BoundaryLabels
data_annot_face_dir: /mnt/isilon/skali/CC3D_filter/cc3d_v1.0_BRepFaceLabels
data_annot_jnc_dir: /mnt/isilon/skali/CC3D_filter/cc3d_v1.0_JunctionLabels
data_root_dir: /mnt/isilon/skali/CC3D_filter
data_scan_dir: /mnt/isilon/skali/CC3D_filter/cc3d_v1.0_scans
dataset_type: CC3D
det_loss: focal
detect_anomaly: false
device: cuda:0
disable_save: false
dropout: 0.0
emb_dims: 128
emb_nn: dgcnn
enable_checkpointing: true
enable_model_summary: true
enable_progress_bar: true
eval_batch_size: 24
fast_debug: false
fast_dev_run: false
ff_dims: 1024
jncOnly: true
log_dir: /mnt/isilon/skali/logs_CC3D
log_every_n_steps: 50
logger: true
lr: 0.0005
lr_steps: !!python/tuple
- 15
- 30
- 45
max_epochs: 100
max_steps: -1
mixed_precision: false
model_name: BRepJd
move_metrics_to_cpu: false
multiple_trainloader_mode: max_size_cycle
n_blocks: 1
n_heads: 4
num_gpus: 1
num_nodes: 1
num_points: 4192
num_sanity_val_steps: 2
overfit_batches: 0.0
pointer: transformer
precision: 32
reload_dataloaders_every_n_epochs: 0
replace_sampler_ddp: true
sampling_type: bjsample
save_weights: false
sync_batchnorm: false
track_grad_norm: -1
train_batch_size: 24
train_only_Boundary: false
train_only_Junction: false
train_only_descriptor: false
